#!/usr/bin/env bash
# Function to display subdomain information
display_info() {
    local subdomain=$1
    local record_type=$(dig +short -t A "$subdomain" | awk 'NR==1 { if ($0 ~ /^[0-9.]+$/) print "A"; else print "Unknown" }')
    local destination=$(dig +short "$subdomain")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Function to display information for specific subdomain
audit_subdomain() {
    local domain=$1
    local subdomain=$2

    if [[ -n $subdomain ]]; then
        display_info "$subdomain.$domain"
    else
	subdomains=("www.hindat.tech" "lb-01.hindat.tech" "web-01.hindat.tech" "web-02.hindat.tech")
	      for sub in "${subdomains[@]}"; do
	          display_info "$sub"
	      done
    fi
}

# Main execution starts here
if [[ $# -eq 0 ]]; then
    echo "Please provide arguments: domain and/or subdomain"
    exit 1
fi

domain=$1
subdomain=$2

audit_subdomain "$domain" "$subdomain"
