#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom HTML file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Start Nginx service
sudo service nginx start
