#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom HTML file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Restart Nginx without systemctl
sudo kill -HUP $(pgrep -f "nginx: master process") 2>/dev/null || true
