#!/usr/bin/env bash
# Configure Nginx redirection
echo '
server {
    listen 80;
    297242-web-01 hindat.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' > /etc/nginx/sites-available/redirect_config

ln -s /etc/nginx/sites-available/redirect_config /etc/nginx/sites-enabled/redirect_config

service nginx reload
