#!/usr/bin/env bash
# Create a custom 404 error page
echo '
server {
    listen 80;
    297242-web-01 hindat.tech;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
        return 404 "Ceci n'est pas une page";
    }
}' > /etc/nginx/sites-available/custom_404

ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/custom_404

service nginx reload
