#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
#  Format: The user USERNAME is part of the GROUP_ID gang, lives in
#+ HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the
#+ passcode PASSWORD, more info about the user here: USER ID INFO

# Store the original IFS value
old_ifs=$IFS

# Open the /etc/passwd file for reading
while IFS=":" read -r username password uid gid info home_dir shell; do
    # Extract the user ID's information
    user_id_info=$(echo "$info" | sed 's/,,/, /g' | sed 's/,/\n/g')

    # Display the user information
    echo "The user $username is part of the $gid gang, lives in $home_dir, and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < /etc/passwd

# Reset the IFS to its original value
IFS=$old_ifs
