#!/usr/bin/env bash
#  This script that displays:
#+ The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed

for file in *; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
        name="${file#*-}"
        echo "$name"
    fi
done
