#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine.

# Use ifconfig to get network interface information and filter for IPv4 addresses
ip_addresses=$(ifconfig | grep -oE "inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | awk '{print $2}')

# Display the IPv4 addresses
for ip in $ip_addresses; do
    echo "$ip"
done
